export const mapResults = [
  {
    name: 'FL',
    value: 11397,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'FL',
    fullName: 'Florida',
    perCapita: '0.56',
    className: '',
  },
  {
    name: 'TX',
    value: 10452,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'TX',
    fullName: 'Texas',
    perCapita: '0.38',
    className: '',
  },
  {
    name: 'CA',
    value: 9753,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'CA',
    fullName: 'California',
    perCapita: '0.25',
    className: '',
  },
  {
    name: 'GA',
    value: 7838,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'GA',
    fullName: 'Georgia',
    perCapita: '0.77',
    className: '',
  },
  {
    name: 'NY',
    value: 5754,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'NY',
    fullName: 'New York',
    perCapita: '0.29',
    className: '',
  },
  {
    name: 'PA',
    value: 5219,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'PA',
    fullName: 'Pennsylvania',
    perCapita: '0.41',
    className: '',
  },
  {
    name: 'IL',
    value: 4224,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'IL',
    fullName: 'Illinois',
    perCapita: '0.33',
    className: '',
  },
  {
    name: 'NC',
    value: 3606,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'NC',
    fullName: 'North Carolina',
    perCapita: '0.36',
    className: '',
  },
  {
    name: 'NJ',
    value: 2880,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'NJ',
    fullName: 'New Jersey',
    perCapita: '0.32',
    className: '',
  },
  {
    name: 'MD',
    value: 2599,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'MD',
    fullName: 'Maryland',
    perCapita: '0.43',
    className: '',
  },
  {
    name: 'AL',
    value: 2404,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'AL',
    fullName: 'Alabama',
    perCapita: '0.50',
    className: '',
  },
  {
    name: 'MI',
    value: 2393,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'MI',
    fullName: 'Michigan',
    perCapita: '0.24',
    className: '',
  },
  {
    name: 'VA',
    value: 2339,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'VA',
    fullName: 'Virginia',
    perCapita: '0.28',
    className: '',
  },
  {
    name: 'OH',
    value: 2254,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'OH',
    fullName: 'Ohio',
    perCapita: '0.19',
    className: '',
  },
  {
    name: 'SC',
    value: 1975,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'SC',
    fullName: 'South Carolina',
    perCapita: '0.40',
    className: '',
  },
  {
    name: 'TN',
    value: 1873,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'TN',
    fullName: 'Tennessee',
    perCapita: '0.28',
    className: '',
  },
  {
    name: 'AZ',
    value: 1707,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'AZ',
    fullName: 'Arizona',
    perCapita: '0.25',
    className: '',
  },
  {
    name: 'LA',
    value: 1694,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'LA',
    fullName: 'Louisiana',
    perCapita: '0.36',
    className: '',
  },
  {
    name: 'NV',
    value: 1394,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'NV',
    fullName: 'Nevada',
    perCapita: '0.48',
    className: '',
  },
  {
    name: 'MO',
    value: 1305,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'MO',
    fullName: 'Missouri',
    perCapita: '0.21',
    className: '',
  },
  {
    name: 'MS',
    value: 1114,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'MS',
    fullName: 'Mississippi',
    perCapita: '0.37',
    className: '',
  },
  {
    name: 'IN',
    value: 1071,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'IN',
    fullName: 'Indiana',
    perCapita: '0.16',
    className: '',
  },
  {
    name: 'MA',
    value: 991,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'MA',
    fullName: 'Massachusetts',
    perCapita: '0.15',
    className: '',
  },
  {
    name: 'WA',
    value: 861,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'WA',
    fullName: 'Washington',
    perCapita: '0.12',
    className: '',
  },
  {
    name: 'CO',
    value: 827,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'CO',
    fullName: 'Colorado',
    perCapita: '0.15',
    className: '',
  },
  {
    name: 'WI',
    value: 749,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'WI',
    fullName: 'Wisconsin',
    perCapita: '0.13',
    className: '',
  },
  {
    name: 'CT',
    value: 726,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'CT',
    fullName: 'Connecticut',
    perCapita: '0.20',
    className: '',
  },
  {
    name: 'MN',
    value: 673,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'MN',
    fullName: 'Minnesota',
    perCapita: '0.12',
    className: '',
  },
  {
    name: 'AR',
    value: 632,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'AR',
    fullName: 'Arkansas',
    perCapita: '0.21',
    className: '',
  },
  {
    name: 'DE',
    value: 552,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'DE',
    fullName: 'Delaware',
    perCapita: '0.58',
    className: '',
  },
  {
    name: 'OK',
    value: 535,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'OK',
    fullName: 'Oklahoma',
    perCapita: '0.14',
    className: '',
  },
  {
    name: 'KY',
    value: 460,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'KY',
    fullName: 'Kentucky',
    perCapita: '0.10',
    className: '',
  },
  {
    name: 'OR',
    value: 416,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'OR',
    fullName: 'Oregon',
    perCapita: '0.10',
    className: '',
  },
  {
    name: 'DC',
    value: 368,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'DC',
    fullName: 'District of Columbia',
    perCapita: '0.55',
    className: '',
  },
  {
    name: 'UT',
    value: 334,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'UT',
    fullName: 'Utah',
    perCapita: '0.11',
    className: '',
  },
  {
    name: 'KS',
    value: 270,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'KS',
    fullName: 'Kansas',
    perCapita: '0.09',
    className: '',
  },
  {
    name: 'IA',
    value: 254,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'IA',
    fullName: 'Iowa',
    perCapita: '0.08',
    className: '',
  },
  {
    name: 'NM',
    value: 214,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'NM',
    fullName: 'New Mexico',
    perCapita: '0.10',
    className: '',
  },
  {
    name: 'RI',
    value: 194,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'RI',
    fullName: 'Rhode Island',
    perCapita: '0.18',
    className: '',
  },
  {
    name: 'HI',
    value: 171,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'HI',
    fullName: 'Hawaii',
    perCapita: '0.12',
    className: '',
  },
  {
    name: 'NE',
    value: 144,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'NE',
    fullName: 'Nebraska',
    perCapita: '0.08',
    className: '',
  },
  {
    name: 'ID',
    value: 143,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'ID',
    fullName: 'Idaho',
    perCapita: '0.09',
    className: '',
  },
  {
    name: 'WV',
    value: 124,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'WV',
    fullName: 'West Virginia',
    perCapita: '0.07',
    className: '',
  },
  {
    name: 'NH',
    value: 109,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'NH',
    fullName: 'New Hampshire',
    perCapita: '0.08',
    className: '',
  },
  {
    name: 'ME',
    value: 97,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'ME',
    fullName: 'Maine',
    perCapita: '0.07',
    className: '',
  },
  {
    name: 'MT',
    value: 73,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'MT',
    fullName: 'Montana',
    perCapita: '0.07',
    className: '',
  },
  {
    name: 'AK',
    value: 70,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'AK',
    fullName: 'Alaska',
    perCapita: '0.09',
    className: '',
  },
  {
    name: 'ND',
    value: 61,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'ND',
    fullName: 'North Dakota',
    perCapita: '0.08',
    className: '',
  },
  {
    name: 'SD',
    value: 61,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'SD',
    fullName: 'South Dakota',
    perCapita: '0.07',
    className: '',
  },
  {
    name: 'VT',
    value: 54,
    issue: 'Incorrect information on your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'VT',
    fullName: 'Vermont',
    perCapita: '0.09',
    className: '',
  },
  {
    name: 'WY',
    value: 38,
    issue: 'Improper use of your report',
    product:
      'Credit reporting, credit repair services, or other personal consumer reports',
    abbr: 'WY',
    fullName: 'Wyoming',
    perCapita: '0.07',
    className: '',
  },
];
