approvedGitRepositories:
  - 'https://github.com/cfpb/design-system-react.git'

defaultSemverRangePrefix: '^'

enableGlobalCache: false

enableMirror: true

enableTelemetry: false

npmPreapprovedPackages:
  - '@cfpb/cfpb-design-system'
  - '@cfpb/design-system-react'

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
