import { TOUR_STEP_TARGETS as STEP } from './tourSelectorConstants';

export { TOUR_SELECTORS, TOUR_STEP_TARGETS } from './tourSelectorConstants';

export const DOCUMENT_STEP_SELECTORS = {
  STEP_1: '.content__hero',
  STEP_2: '.m-pagination__btn-next',
  STEP_3: '.saved__search-panel div:nth-child(2)',
  STEP_4: '.back-to-results',
};

export const GEO_STEP_SELECTORS = {
  STEP_1: STEP.INDEX,
  STEP_2: STEP.HELP_LINKS,
  STEP_3: STEP.VIEWS,
  STEP_4: STEP.FILTERS,
  STEP_5: STEP.DATE_RECEIVED,
  STEP_6: STEP.PRODUCT_ISSUE,
  STEP_7: STEP.SHOW_HIDE,
  STEP_8: STEP.SEARCH_BAR,
  STEP_9: STEP.SEARCH_SUMMARY,
  STEP_10: STEP.EXPORT_DATA,
  STEP_11: STEP.PRINT_PAGE,
  STEP_12: STEP.MAP_SHADING,
  STEP_13: STEP.TILE_MAP,
  STEP_14: STEP.MAP_ROW_CHARTS,
  STEP_15: STEP.TABBED_NAVIGATION,
};

export const LIST_COMPLAINTS_SELECTORS = {
  STEP_1: STEP.INDEX,
  STEP_2: STEP.HELP_LINKS,
  STEP_3: STEP.VIEWS,
  STEP_4: STEP.FILTERS,
  STEP_5: STEP.DATE_RECEIVED,
  STEP_6: STEP.PRODUCT_ISSUE,
  STEP_7: STEP.SHOW_HIDE,
  STEP_8: STEP.SEARCH_BAR,
  STEP_9: STEP.SEARCH_SUMMARY,
  STEP_10: STEP.EXPORT_DATA,
  STEP_11: STEP.PRINT_PAGE,
  STEP_12: STEP.SELECT_SIZE,
  STEP_13: STEP.SELECT_SORT,
  STEP_14: STEP.NARRATIVES,
  STEP_15: STEP.RESULTS,
  STEP_16: STEP.COMPLAINT_DETAIL,
  STEP_17: STEP.TABBED_NAVIGATION,
};

export const TRENDS_SELECTORS = {
  STEP_1: STEP.INDEX,
  STEP_2: STEP.HELP_LINKS,
  STEP_3: STEP.VIEWS,
  STEP_4: STEP.FILTERS,
  STEP_5: STEP.DATE_RECEIVED,
  STEP_6: STEP.PRODUCT_ISSUE,
  STEP_7: STEP.SHOW_HIDE,
  STEP_8: STEP.SEARCH_BAR,
  STEP_9: STEP.SEARCH_SUMMARY,
  STEP_10: STEP.EXPORT_DATA,
  STEP_11: STEP.PRINT_PAGE,
  STEP_12: STEP.SELECT_LENS,
  STEP_13: STEP.SELECT_INTERVAL,
  STEP_14: STEP.ROW_CHARTS,
  STEP_15: STEP.TABBED_NAVIGATION,
};
